### ISSUE TITLE
Extension doesn't work in code blocks

### ISSUE THREAD

**Issue by adi-** [jambonrose/markdown_subscript_extension#1]
Subscript (and superscript) doesn't work in inline and block code blocks.

i.e.:

`12^23^ ~sd~`

```
12^23^ ~sd~
```

**Comment by jambonrose** [comment]
This is actually by design. To my knowledge, no programming language accepts superscript or subscript text as input. However, programming languages do make use of the `~` character (R comes to mind), and `^` is used quite frequently in regular expressions or in bit arithmetic. 

Getting superscript and subscript in code blocks is thus a new feature. The new feature must also be conditional: it must not be the default, given the reasons above.

HTML appears to support the use of `<sup>` and `<sub>` within `<pre>` tags, so this is a potentially realizable feature. What's more, Markdown does not treat `^` or `~` as special characters, avoiding weird interactions between these extensions and the code block functionality.

That said, I'm still not entirely convinced this is a useful feature. What is your use case? What are you putting in code blocks that requires superscript or subscript?

**Comment by adi-** [comment]
Yeah, you are right. My mistake.
